spring:
  data:
    rest:
      basePath: /api
  logging:
    config: classpath:logback.xml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    jackson:
      serialization:
        indent_output: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


server:
  port: 7001
debug: false

management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
