spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:9999
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}

  security:
    user:
      name: admin
      password: 123456


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
