spring:
  data:
    rest:
      basePath: /api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: huruiyi
    password: huruiyi
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    serialization:
      indent-output: true
server:
  port: 7001
debug: false

management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true

logging:
  config: classpath:logback.xml
