server:
  port: 9999

spring:
  application:
    name: admin-server
  boot:
    admin:
      instance-auth:
        default-user-name: ${spring.security.user.name}
        default-password: ${spring.security.user.password}
      client:
        url: http://localhost:9999
        username: ${spring.security.user.name}
        password: ${spring.security.user.password}

  security:
    user:
      name: admin
      password: 123456

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
    health:
      show-details: ALWAYS


security:
  user:
    name: admin
    password: 123456

#logging:
#  level: debug