spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flowable?nullCatalogMeansCurrent=true
    username: root
    password: fairy-vip

flowable:
  async-executor-activate: true
  database-schema-update: true

server:
  servlet:
    context-path:
  port: 9090
